nbs_cv_homepage:
    path:       /
    defaults:
        _controller:    FrameworkBundle:Redirect:urlRedirect
        path:           /fabien
        permanent:      true

# nbs_cv_testmail:
#     path:       /mailtest
#     defaults:
#         _controller:    NbsCVBundle:TestMail:index

mremi_contact_form:
    path:       /{cvxmlfile}/{_locale}/contact
    defaults:
        _controller:    mremi_contact.contact_controller:indexAction
        _locale:        en
        cvxmlfile:      fabien

mremi_contact_confirmation:
    path:       /{cvxmlfile}/{_locale}/contact/confirmation
    defaults:
        _controller:    mremi_contact.contact_controller:confirmAction
        _locale:        en
        cvxmlfile:      fabien
